# Generated by Django 2.1.7 on 2019-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='courses name')),
                ('slug', models.SlugField(verbose_name='shortcut')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('image', models.ImageField(upload_to='courses/images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
    ]
