# Generated by Django 2.1.7 on 2019-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190312_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, verbose_name='courses name'),
        ),
    ]
